<link href="{{ asset('bower_components/bower-package/css/googleapis.css') }}" rel="stylesheet">
<link href="{{ asset('bower_components/bower-package/css/googleapiss.css') }}" rel="stylesheet">
<link href="{{ asset('bower_components/bower-package/css/googleapisss.css') }}" rel="stylesheet">
<link rel="stylesheet" href="{{ asset('bower_components/open-iconic/font/css/open-iconic-bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/bower-package/css/animate.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/bower-package/css/owl.carousel.min.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/bower-package/css/owl.theme.default.min.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/bower-package/css/magnific-popup.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/aos/dist/aos.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/bower-package/css/ionicons.min.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/bower-package/css/bootstrap-datepicker.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/bower-package/css/flaticon.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/bower-package/css/icomoon.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/bower-package/css/style.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/Font-Awesome/css/fontawesome.min.css') }}">
<link href="{{ mix('css/custom.css') }}" rel="stylesheet">
