<link href="{{ asset('bower_components/bower-package/css/google-apis.css') }}" rel="stylesheet">
<link href="{{ asset('bower_components/bower-package/css/google-api-ss.css') }}" rel="stylesheet">
<link href="{{ asset('bower_components/bower-package/css/google-api-sss.css') }}" rel="stylesheet">
<link rel="stylesheet" href="{{ asset('bower_components/open-iconic/font/css/open-iconic-bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/bower-package/css/animate.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/bower-package/css/owl.carousel.min.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/bower-package/css/owl.theme.default.min.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/bower-package/css/fic-popup.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/bower-package/css/aos.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/bower-package/css/ion-icons.min.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/bower-package/css/bootstrap-datepicker.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/bower-package/css/flat-icon.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/bower-package/css/ico-moon.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/bower-package/css/style.css') }}">
<link rel="stylesheet" href="{{ asset('bower_components/Font-Awesome/css/fontawesome.min.css') }}">
<link href="{{ mix('css/custom.css') }}" rel="stylesheet">
